# -*- coding: utf-8 -*-
"""Travel-planner-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9qserUkxmNgg9UL4ZU6CNYJrIlbcREf
"""

import requests
from urllib.parse import quote
from rich import print
from rich.markdown import Markdown

#Call the SheCodes Weather API
def display_current_weather(location):
  """ Get the real-time temperature and condition in the location"""
  api_key = "749b4a3937d79a07ao7fd73bd32t1f04"
  api_url = f"https://api.shecodes.io/weather/v1/current?query={location}&key={api_key}&units=metric"

  response = requests.get(api_url)
  response_data = response.json()

  temperature = round(response_data['temperature']['current'])
  condition = response_data['condition']['description']

  print(f"[bold green]The current temperature in [bold]{location}[/bold] is {temperature}°C, {condition}[/bold green]")

#Get some user inputs (origin, destination, duration)
def generate_itinerary(origin, destination, duration):
    print(f"\n\nGenerating itinerary from {origin} to {destination}...")
    prompt = f"Generate a travel itinerary from {origin} to {destination} for {duration} days. This is a road trip, keep it short, less than 15 lines, add some emojis (not more than 5) to make readable. Add an estimated price and weather conditions of each day in Euros."

    context = "You are a travel specialist and know the best tourist spots around the world"
    #Call the SheCodes AI API (to get the itinerary)
    api_key = "749b4a3937d79a07ao7fd73bd32t1f04"
    api_url = f"https://api.shecodes.io/ai/v1/generate?prompt={prompt}&context={context}&key={api_key}"

    response = requests.get(api_url)
    response_data = response.json()
    itinerary = Markdown(response_data["answer"])

    print(itinerary)


#Final touches (add credit, few improvements, potential)
def welcome():
  print("[bold magenta]Welcome to the AI Travel Itenerary Planner[/bold magenta]")

def credit():
  print("[bold magenta]The AI Travel Itinerary Planner was built by [bold yellow]Mélanie Parmentier[/bold yellow], Thank you for using it 🐞 [/bold magenta]")

welcome()


#user inputs
origin = input("What city does your trip start from?").strip()
destination = input("What city is your trip going to?").strip()
duration = input("How many days will your trip last? (enter a number only, i.e 5)").strip()

#Display the itinerary
#Display the weather in the origin and the destination
if origin and destination and duration.isdigit():
  display_current_weather(origin)
  display_current_weather(destination)
  generate_itinerary(origin, destination, duration)
  credit()
else:
  print("Please try again, Make sure you enter valid information")

import requests
from rich import print
from rich.markdown import Markdown

def display_current_weather(location):
  """ Get the real time temperature and condition in a location """
  api_key = "2046c535afeb092fo82f1d306d8a2b2t"
  api_url = f"https://api.shecodes.io/weather/v1/current?query={location}&key={api_key}&units=metric"

  response = requests.get(api_url)
  response_data = response.json()

  temperature = round(response_data['temperature']['current'])
  condition = response_data['condition']['description']

  print(f"The current temperature in [bold]{location}[/bold] is [bold]{temperature}°C[/bold], {condition}.\n")

def generate_itinerary(origin, destination, duration):
  """ Generate travel itinerary between 2 places using AI """
  print(f"\n\nGenerating itinerary from {origin} to {destination}..\n")
  prompt = f"Generate a travel itinerary from {origin} to {destination} in {duration} days. This is a road, keep it short, less than 15 lines, add some emojis (not more than 5) to make readable. Add an estimated price of each day in euros"

  context = "You a travel specialist and know the best tourist spots around the world"
  api_key = "2046c535afeb092fo82f1d306d8a2b2t"
  api_url = f"https://api.shecodes.io/ai/v1/generate?prompt={prompt}&context={context}&key={api_key}"

  response = requests.get(api_url)
  response_data = response.json()
  itinerary = Markdown(response_data['answer'])

  print(itinerary)

# User inputs
origin = input("What city does your trip start from? ")
destination = input("What city is your trip going to? ")
duration = input("How many days will your trip last? (enter a number only, i.e 5) ")

if origin and destination and duration.isdigit():
  display_current_weather(origin)
  display_current_weather(destination)
  generate_itinerary(origin, destination, duration)
else:
  print("Please try again. Make sure you enter valid information")